version: '3.4'
services:
    master:
        container_name: jenkins-master
        image: 'mateothegreat/docker-alpine-jenkins-gcloud:latest'
        ports:
            - '8080:8080'
            - '50001:50001'
        volumes:
            - '$PWD/jenkins_home:/var/jenkins_home'
        restart: always
